name: Automatic Data Update

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  DataUpdater:
    name: Automatic Data Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js v18
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Run updater
        run: node --experimental-json-modules scripts/update-css.mjs
      - name: Run prettier on the code
        run: yarn format
      - name: Commit any changes and create a pull request
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, exiting with code 0"
            exit 0;
          else
            git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
            git config --local user.email "${GITHUB_EMAIL}";
            git config --local user.name "${GITHUB_USER}";
            git checkout -b update-css/$(date +%F-%H-%M);
            git commit -sam "feat: update transcript css";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
            gh pr create -t "feat: update transcript css" -b "*bleep bloop* I updated the transcript css" -B main;
          fi
