name: Automatic Data Update

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  DataUpdater:
    name: Automatic Data Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Use Node.js v18
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Run updater
        run: true || node --experimental-json-modules scripts/update-css.mjs
      - name: Run prettier on the code
        run: yarn format
      - name: Commit any changes and create a pull request
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, exiting with code 0"
            exit 0;
          else
            git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
            git config --local user.email "${GITHUB_EMAIL}";
            git config --local user.name "${GITHUB_USER}";
            git checkout -b update-css/$(date +%F-%H-%M);
            git commit -sam "feat: update transcript css";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
            gh pr create -t "feat: update transcript css" -b "*bleep bloop* I updated the transcript css" -B main;
          fi
